using AshenSpire.Domain.Original;
using Newtonsoft.Json.Linq;
internal static class CustomRunChecks
{
 internal static void Run(string root)
 {
 Directory.CreateDirectory(Path.Combine(root,"TestResults/Parity"));
// Native custom-rule differential and public setup/draft tests; no Unity dependencies.
var contentRoot=Path.Combine(root,"GameContent/Unity/Original");
var catalog=new OriginalContentCatalog(File.ReadAllText(Path.Combine(contentRoot,"content.json")));var data=catalog.Data();
var mechanics=JObject.Parse(File.ReadAllText(Path.Combine(contentRoot,"mechanics.json")));var supplement=JObject.Parse(File.ReadAllText(Path.Combine(contentRoot,"event-choices.json")));
var progression=new AttributeProgression(JObject.Parse(File.ReadAllText(Path.Combine(contentRoot,"progression.json"))));
var expected=JObject.Parse(File.ReadAllText(Path.Combine(root,"UnityTests/Parity/CustomRunChecks.json")));var rules=new OriginalCustomRunRules(data);int checks=0;
void Assert(bool value,string message){checks++;if(!value)throw new Exception(message);}
bool Same(JToken a,JToken b){if(a is JValue av && av.Value==null)a=JValue.CreateNull();if(b is JValue bv && bv.Value==null)b=JValue.CreateNull();if(a==null||b==null)return a==b;if(a.Type is JTokenType.Float or JTokenType.Integer&&b.Type is JTokenType.Float or JTokenType.Integer)return(double)a==(double)b;if(a is JObject ao&&b is JObject bo)return ao.Count==bo.Count&&ao.Properties().All(p=>Same(p.Value,bo[p.Name]));if(a is JArray aa&&b is JArray ba)return aa.Count==ba.Count&&aa.Zip(ba).All(pair=>Same(pair.First,pair.Second));return JToken.DeepEquals(a,b);}
void Equal(JToken a,JToken b,string message)=>Assert(Same(a,b),message+"\nEXPECTED "+b+"\nACTUAL "+a);
JObject Player(string classId){var creator=new CreationModel(catalog,classId,"standard",progression);var kit=(string)catalog.Table("equipment.startingKits").First(k=>(string)k["classId"]==classId&&(bool?)k["baseline"]==true)["id"];return new OriginalCharacterBuilder(catalog,progression,mechanics).Build(creator,kit);}
OriginalGameSession Start(string classId,uint seed,JObject custom=null,string keepsake="none")=>OriginalGameSession.StartConfigured(catalog,supplement,mechanics,Player(classId),seed,new JObject{["custom"]=custom??new JObject(),["keepsakeId"]=keepsake});
void Rejected(OriginalGameSession game,Action command,string message){var before=game.Snapshot();bool refused=false;try{command();}catch(ArgumentException){refused=true;}catch(InvalidOperationException){refused=true;}Assert(refused,message);Equal(game.Snapshot(),before,message+" rollback");}
foreach(var row in expected["rules"]){var run=new JObject{["custom"]=row["custom"].DeepClone(),["actNumber"]=row["actNumber"].DeepClone()};Equal(OriginalCustomRunRules.ActiveMods((JObject)row["custom"]),row["active"],"active");Equal(new JValue(OriginalCustomRunRules.IsCustom((JObject)row["custom"])),row["isCustom"],"classification");Equal(new JValue(rules.ContentAct(run)),row["contentAct"],"content act");Equal(rules.CombatOptions(run,(string)row["pool"]),row["combat"],"combat options");Equal(new JValue(rules.ShopPriceMultiplier(run)),row["price"],"shop multiplier");}
foreach(var row in expected["sealed"]){var game=Start((string)row["classId"],(uint)row["seed"],new JObject{["deckMode"]="sealed"});Equal(new JArray(game.RunPlayer["deck"].Select(c=>c["cardId"])),row["ids"],"sealed original picks");Equal(game.RunPlayer["streamCounters"]["misc"],row["rng"]["misc"],"sealed RNG");Assert((bool)game.RunPlayer["isCustom"]&&!(bool)game.RunPlayer["countsForWinRate"],"sealed custom telemetry");Assert((int)game.RunPlayer["equipmentAttackSlotCount"]==0,"sealed original ordinary basics");Equal(OriginalGameSession.Restore(game.Snapshot()).Snapshot(),game.Snapshot(),"sealed resume");}
foreach(var row in expected["draft"]){var game=Start((string)row["classId"],(uint)row["seed"],new JObject{["deckMode"]="draft"});Assert(game.Phase==OriginalRunPhase.Draft,"starts in draft");Assert((int)game.RunPlayer["streamCounters"]["map"]==0,"map not rolled before picks");Rejected(game,()=>game.PickDraft("__invalid__"),"invalid draft atomic");foreach(var round in row["rounds"]){Equal(game.DraftChoices,round["offer"],"original draft offer");Equal(game.RunPlayer["streamCounters"]["cardRewards"],round["rng"]["cardRewards"],"original draft RNG");var restored=OriginalGameSession.Restore(JObject.Parse(game.Snapshot().ToString()));game.PickDraft((string)round["picked"]);restored.PickDraft((string)round["picked"]);Equal(game.Snapshot(),restored.Snapshot(),"draft saved offer stays deterministic");}Assert(game.Phase==OriginalRunPhase.Map&&(int)game.RunPlayer["streamCounters"]["map"]>0,"map generated after third pick");Assert(game.RunPlayer["deck"].Count()==10,"draft final count");}
var native=new OriginalRunRules(data);
foreach(var row in expected["rewards"]){var random=new RandomStreams((uint)row["seed"]);var run=new JObject{["class"]=row["classId"],["relics"]=new JArray(),["custom"]=new JObject{["mods"]=new JObject{["chaosRewards"]=true}}};Equal(native.Cards(random,(string)row["pool"],run),row["ids"],"original chaos reward picks");Equal(JObject.FromObject(random.Snapshot()),row["rng"],"chaos reward streams");}
foreach(var row in expected["shops"]){foreach(var modifier in new[]{"expensiveShops","hoarder","both"}){var run=new JObject{["class"]=row["classId"],["relics"]=new JArray(),["custom"]=new JObject{["mods"]=new JObject{["expensiveShops"]=modifier!="hoarder",["hoarder"]=modifier!="expensiveShops"}}};var random=new RandomStreams((uint)row["seed"]);var stock=native.Shop(random,run);var wanted=(JObject)row["stock"].DeepClone();double mult=modifier=="both"?3:modifier=="hoarder"?2:1.5;foreach(var kind in new[]{"cards","flasks","relics"})foreach(var item in wanted[kind])item["cost"]=(int)Math.Ceiling((int)item["cost"]*mult);wanted["removeCost"]=(int)Math.Ceiling((int)wanted["removeCost"]*mult);Equal(stock,wanted,"original custom shop");Equal(JObject.FromObject(random.Snapshot()),row["rng"],"custom shop RNG unchanged");}}
foreach(var row in expected["rest"])Equal(new JValue(native.RestHeal((JObject)row["run"])),row["heal"],"original halved shrine heal");
foreach(var row in expected["combatStarts"]){var options=rules.CombatOptions((JObject)row["run"],(string)row["pool"]);var player=(JObject)row["player"].DeepClone();player["startStatuses"]=options["playerStatuses"].DeepClone();var c=new CombatSession(catalog,mechanics,new RandomStreams((uint)row["seed"]),player,((JArray)player["deck"]).OfType<JObject>(),row["enemyIds"].Values<string>(),card=>catalog.Record("cards",(string)card["cardId"]),(double)options["hpMult"],(JArray)options["enemyStatuses"]);Equal(c.Enemies,row["enemies"],"original custom combat enemy state");Equal(c.Player["statuses"],row["playerStatuses"],"original custom player buffs");Equal(c.Snapshot()["events"],row["events"],"original custom combat startup order");Equal(c.Snapshot()["rng"],row["rng"],"original custom combat RNG");Equal(CombatSession.Restore(catalog,mechanics,c.Snapshot(),card=>catalog.Record("cards",(string)card["cardId"])).Snapshot(),c.Snapshot(),"custom combat restore");}
var basic=Start("reaver",123);Assert(!(bool)basic.RunPlayer["isCustom"]&&(bool)basic.RunPlayer["countsForWinRate"],"seed-only standard remains standard");
var hoard=Start("reaver",123,new JObject{["mods"]=new JObject{["hoarder"]=true,["cursedStart"]=true}});Assert((int)hoard.RunPlayer["cinders"]==(int)basic.RunPlayer["cinders"]+250,"hoarder opening currency");Assert(hoard.RunPlayer["deck"].Count(c=>(string)c["cardId"]=="guilt")==1,"cursed start exactly once");
foreach(var keepsake in new[]{"oldCinder","travelersFlask","whetstoneMemory"}){var game=Start("reaver",123,null,keepsake);if(keepsake=="oldCinder")Assert((int)game.RunPlayer["cinders"]==(int)basic.RunPlayer["cinders"]+50,"keepsake cinders");if(keepsake=="travelersFlask")Assert((int)game.RunPlayer["flaskCharges"]["hp"]==(int)basic.RunPlayer["flaskCharges"]["hp"]+1,"keepsake flask");if(keepsake=="whetstoneMemory")Assert(((JObject)game.RunPlayer["itemUpgradeLevels"]).Properties().Any(p=>(int)p.Value==1),"keepsake smith");Equal(OriginalGameSession.Restore(game.Snapshot()).Snapshot(),game.Snapshot(),"keepsake not reapplied at load");}
foreach(var bad in new[]{new JObject{["ascension"]=-1},new JObject{["ascension"]=7},new JObject{["mods"]=new JObject{["unknown"]=true}},new JObject{["mods"]=new JObject{["hoarder"]="yes"}},new JObject{["deckMode"]="practice"},new JObject{["mapShape"]=new JObject{["floors"]=4}}}){bool refused=false;try{Start("reaver",123,bad);}catch(ArgumentException){refused=true;}catch(NotSupportedException){refused=true;}Assert(refused,"invalid configuration rejected");}
foreach(var fault in new[]{"customType","classification","draftRound","draftOffer"}){var snapshot=Start("reaver",123,new JObject{["deckMode"]="draft"}).Snapshot();if(fault=="customType")snapshot["run"]["custom"]="bad";if(fault=="classification")snapshot["run"]["isCustom"]=false;if(fault=="draftRound")((JObject)snapshot["run"]["room"]["draft"]).Remove("round");if(fault=="draftOffer")snapshot["run"]["room"]["draft"]["offer"]=new JArray("__invalid__");bool refused=false;try{OriginalGameSession.Restore(snapshot);}catch(ArgumentException){refused=true;}Assert(refused,"corrupted custom snapshot: "+fault);}
Console.WriteLine($"PASS {checks} custom configuration, original-rule, draft, keepsake and save checks.");File.WriteAllText(Path.Combine(root,"TestResults/Parity/CustomRunChecks-test-result.json"),new JObject{["checks"]=checks,["result"]="pass",["originalBaseline"]=expected["baseline"]}.ToString());
 }

}
