// GENERATED by tools/unity-content-schema.mjs from src/model/schemas.js. Do not edit by hand:
// change the HTML schema (or the tool), then run: node tools/unity-content-schema.mjs
// Read by OriginalContentValidation; the descriptor kinds are those of validate.js walkSchema.
namespace AshenSpire.Domain.Original
{
    public static class OriginalContentSchema
    {
        public const string Json = @"{
 ""source"": ""src/model/schemas.js"",
 ""tables"": {
  ""attributes"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""label"": {
     ""k"": ""str""
    },
    ""shortLabel"": {
     ""k"": ""str""
    },
    ""order"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""disclosure"": {
     ""k"": ""enum"",
     ""values"": [
      ""face"",
      ""reveal""
     ]
    },
    ""sense"": {
     ""k"": ""str""
    }
   }
  },
  ""creationModes"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""label"": {
     ""k"": ""str""
    },
    ""baseline"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""bonusPool"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""minimum"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""maximum"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""belowBaseline"": {
     ""k"": ""enum"",
     ""values"": [
      ""forbid"",
      ""allow""
     ]
    },
    ""redistribution"": {
     ""k"": ""enum"",
     ""values"": [
      ""fixedTotal""
     ]
    },
    ""equipmentProfiles"": {
     ""k"": ""map"",
     ""of"": {
      ""k"": ""obj"",
      ""fields"": {
       ""baseValue"": {
        ""k"": ""num"",
        ""opt"": true
       },
       ""scalingStat"": {
        ""k"": ""ref"",
        ""reg"": ""attributes"",
        ""opt"": true
       },
       ""pointsPerTier"": {
        ""k"": ""num"",
        ""opt"": true
       },
       ""rounding"": {
        ""k"": ""enum"",
        ""values"": [
         ""floor"",
         ""ceil"",
         ""round""
        ],
        ""opt"": true
       },
       ""gainPerTier"": {
        ""k"": ""num"",
        ""opt"": true
       },
       ""cap"": {
        ""k"": ""num"",
        ""opt"": true
       }
      }
     },
     ""opt"": true
    }
   }
  },
  ""cards"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""name"": {
     ""k"": ""str""
    },
    ""class"": {
     ""k"": ""str""
    },
    ""rarity"": {
     ""k"": ""enum"",
     ""values"": [
      ""starter"",
      ""common"",
      ""uncommon"",
      ""rare"",
      ""special""
     ]
    },
    ""cost"": {
     ""k"": ""union"",
     ""anyOf"": [
      {
       ""k"": ""num"",
       ""int"": true
      },
      {
       ""k"": ""enum"",
       ""values"": [
        ""X""
       ]
      }
     ]
    },
    ""manaCost"": {
     ""k"": ""num"",
     ""int"": true,
     ""opt"": true
    },
    ""staminaCost"": {
     ""k"": ""num"",
     ""int"": true,
     ""opt"": true
    },
    ""type"": {
     ""k"": ""enum"",
     ""values"": [
      ""attack"",
      ""skill"",
      ""power"",
      ""curse"",
      ""status""
     ]
    },
    ""damageSchool"": {
     ""k"": ""enum"",
     ""values"": [
      ""physical"",
      ""magic"",
      ""arcane"",
      ""holy"",
      ""fire""
     ],
     ""opt"": true
    },
    ""exposureBuildupPerHit"": {
     ""k"": ""num"",
     ""int"": true,
     ""opt"": true
    },
    ""keywords"": {
     ""k"": ""arr"",
     ""of"": {
      ""k"": ""ref"",
      ""reg"": ""keywords""
     }
    },
    ""effects"": {
     ""k"": ""effects""
    },
    ""textTemplate"": {
     ""k"": ""str""
    },
    ""upgrade"": {
     ""k"": ""obj"",
     ""fields"": {
      ""name"": {
       ""k"": ""str"",
       ""opt"": true
      },
      ""cost"": {
       ""k"": ""union"",
       ""anyOf"": [
        {
         ""k"": ""num"",
         ""int"": true
        },
        {
         ""k"": ""enum"",
         ""values"": [
          ""X""
         ]
        }
       ],
       ""opt"": true
      },
      ""manaCost"": {
       ""k"": ""num"",
       ""int"": true,
       ""opt"": true
      },
      ""staminaCost"": {
       ""k"": ""num"",
       ""int"": true,
       ""opt"": true
      },
      ""effects"": {
       ""k"": ""effects"",
       ""opt"": true
      },
      ""keywords"": {
       ""k"": ""arr"",
       ""of"": {
        ""k"": ""ref"",
        ""reg"": ""keywords""
       },
       ""opt"": true
      },
      ""textTemplate"": {
       ""k"": ""str"",
       ""opt"": true
      }
     },
     ""opt"": true
    },
    ""icon"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""flavor"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""script"": {
     ""k"": ""ref"",
     ""reg"": ""scripts"",
     ""opt"": true
    }
   }
  },
  ""resources"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""name"": {
     ""k"": ""str""
    },
    ""glyph"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""tint"": {
     ""k"": ""str""
    },
    ""weight"": {
     ""k"": ""enum"",
     ""values"": [
      ""normal"",
      ""skinny""
     ]
    },
    ""order"": {
     ""k"": ""num""
    },
    ""surfaces"": {
     ""k"": ""arr"",
     ""of"": {
      ""k"": ""enum"",
      ""values"": [
       ""main"",
       ""model""
      ]
     }
    },
    ""source"": {
     ""k"": ""str""
    },
    ""domainMax"": {
     ""k"": ""num"",
     ""opt"": true
    },
    ""band"": {
     ""k"": ""str"",
     ""opt"": true
    }
   }
  },
  ""relics"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""name"": {
     ""k"": ""str""
    },
    ""rarity"": {
     ""k"": ""enum"",
     ""values"": [
      ""starter"",
      ""common"",
      ""uncommon"",
      ""rare"",
      ""boss""
     ]
    },
    ""pool"": {
     ""k"": ""enum"",
     ""values"": [
      ""reward"",
      ""quest""
     ],
     ""opt"": true
    },
    ""textTemplate"": {
     ""k"": ""str""
    },
    ""triggers"": {
     ""k"": ""triggers""
    },
    ""passives"": {
     ""k"": ""obj"",
     ""fields"": {
      ""runeGainMult"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""eliteExtraCardReward"": {
       ""k"": ""bool"",
       ""opt"": true
      },
      ""flaskPowerMult"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""revealUnknown"": {
       ""k"": ""bool"",
       ""opt"": true
      },
      ""shrineHealMult"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""shrineNoRest"": {
       ""k"": ""bool"",
       ""opt"": true
      },
      ""powerCostReduction"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""poiseThresholdAdd"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""swapCostDelta"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""modifiers"": {
       ""k"": ""arr"",
       ""of"": {
        ""k"": ""any""
       },
       ""opt"": true
      }
     },
     ""opt"": true
    },
    ""icon"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""flavor"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""script"": {
     ""k"": ""ref"",
     ""reg"": ""scripts"",
     ""opt"": true
    }
   }
  },
  ""statuses"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""name"": {
     ""k"": ""str""
    },
    ""icon"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""tint"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""stackMode"": {
     ""k"": ""enum"",
     ""values"": [
      ""add"",
      ""refresh"",
      ""unique""
     ]
    },
    ""decay"": {
     ""k"": ""union"",
     ""anyOf"": [
      {
       ""k"": ""enum"",
       ""values"": [
        ""none"",
        ""perTurnEnd"",
        ""onConsume""
       ]
      },
      {
       ""k"": ""obj"",
       ""fields"": {
        ""duration"": {
         ""k"": ""num"",
         ""int"": true
        }
       }
      }
     ]
    },
    ""instancePresentation"": {
     ""k"": ""obj"",
     ""fields"": {
      ""valueToken"": {
       ""k"": ""enum"",
       ""values"": [
        ""stacks"",
        ""percent""
       ]
      },
      ""durationToken"": {
       ""k"": ""enum"",
       ""values"": [
        ""turns""
       ]
      }
     },
     ""opt"": true
    },
    ""meter"": {
     ""k"": ""obj"",
     ""fields"": {
      ""max"": {
       ""k"": ""num"",
       ""int"": true
      },
      ""growthMult"": {
       ""k"": ""num""
      },
      ""onFill"": {
       ""k"": ""effects""
      }
     },
     ""opt"": true
    },
    ""proc"": {
     ""k"": ""obj"",
     ""fields"": {
      ""threshold"": {
       ""k"": ""num"",
       ""int"": true
      },
      ""burstPercent"": {
       ""k"": ""num""
      },
      ""burstMin"": {
       ""k"": ""num"",
       ""int"": true
      },
      ""burstMax"": {
       ""k"": ""num"",
       ""int"": true
      },
      ""poiseDamage"": {
       ""k"": ""num"",
       ""int"": true,
       ""opt"": true
      },
      ""stagger"": {
       ""k"": ""bool"",
       ""opt"": true
      },
      ""effects"": {
       ""k"": ""effects"",
       ""opt"": true
      },
      ""resistance"": {
       ""k"": ""obj"",
       ""fields"": {
        ""status"": {
         ""k"": ""ref"",
         ""reg"": ""statuses""
        },
        ""tags"": {
         ""k"": ""arr"",
         ""of"": {
          ""k"": ""str""
         }
        }
       },
       ""opt"": true
      }
     },
     ""opt"": true
    },
    ""resists"": {
     ""k"": ""obj"",
     ""fields"": {
      ""status"": {
       ""k"": ""ref"",
       ""reg"": ""statuses""
      },
      ""percent"": {
       ""k"": ""num""
      }
     },
     ""opt"": true
    },
    ""taggedVulnerability"": {
     ""k"": ""obj"",
     ""fields"": {
      ""tags"": {
       ""k"": ""arr"",
       ""of"": {
        ""k"": ""str""
       }
      },
      ""mult"": {
       ""k"": ""num""
      },
      ""stacking"": {
       ""k"": ""enum"",
       ""values"": [
        ""additive"",
        ""multiplicative""
       ]
      }
     },
     ""opt"": true
    },
    ""schoolDamageVulnerability"": {
     ""k"": ""obj"",
     ""fields"": {
      ""school"": {
       ""k"": ""enum"",
       ""values"": [
        ""physical"",
        ""magic"",
        ""arcane"",
        ""holy"",
        ""fire""
       ]
      }
     },
     ""opt"": true
    },
    ""modifiers"": {
     ""k"": ""obj"",
     ""fields"": {
      ""damageDealtMult"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""damageTakenMult"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""blockGainedMult"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""attackDamageAdd"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""blockAdd"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""skipTurn"": {
       ""k"": ""bool"",
       ""opt"": true
      },
      ""retainBlock"": {
       ""k"": ""bool"",
       ""opt"": true
      },
      ""blockCap"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""meterMaxGrowthDisabled"": {
       ""k"": ""bool"",
       ""opt"": true
      }
     },
     ""opt"": true
    },
    ""hooks"": {
     ""k"": ""triggers"",
     ""opt"": true
    },
    ""tooltip"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""script"": {
     ""k"": ""ref"",
     ""reg"": ""scripts"",
     ""opt"": true
    }
   }
  },
  ""stances"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""name"": {
     ""k"": ""str""
    },
    ""icon"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""onEnter"": {
     ""k"": ""effects"",
     ""opt"": true
    },
    ""modifiers"": {
     ""k"": ""obj"",
     ""fields"": {
      ""damageDealtMult"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""damageTakenMult"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""blockGainedMult"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""attackDamageAdd"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""blockAdd"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""skipTurn"": {
       ""k"": ""bool"",
       ""opt"": true
      },
      ""retainBlock"": {
       ""k"": ""bool"",
       ""opt"": true
      },
      ""blockCap"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""meterMaxGrowthDisabled"": {
       ""k"": ""bool"",
       ""opt"": true
      }
     },
     ""opt"": true
    },
    ""hooks"": {
     ""k"": ""triggers"",
     ""opt"": true
    },
    ""tooltip"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""script"": {
     ""k"": ""ref"",
     ""reg"": ""scripts"",
     ""opt"": true
    }
   }
  },
  ""keywords"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""name"": {
     ""k"": ""str""
    },
    ""tooltip"": {
     ""k"": ""str""
    }
   }
  },
  ""enemies"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""name"": {
     ""k"": ""str""
    },
    ""hp"": {
     ""k"": ""arr"",
     ""of"": {
      ""k"": ""num"",
      ""int"": true
     },
     ""len"": 2
    },
    ""poiseMax"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""levelProfile"": {
     ""k"": ""obj"",
     ""fields"": {
      ""min"": {
       ""k"": ""num"",
       ""int"": true
      },
      ""max"": {
       ""k"": ""num"",
       ""int"": true
      }
     }
    },
    ""moves"": {
     ""k"": ""map"",
     ""of"": {
      ""k"": ""obj"",
      ""fields"": {
       ""intent"": {
        ""k"": ""enum"",
        ""values"": [
         ""attack"",
         ""block"",
         ""buff"",
         ""debuff"",
         ""unknown""
        ]
       },
       ""damage"": {
        ""k"": ""num"",
        ""int"": true,
        ""opt"": true
       },
       ""hits"": {
        ""k"": ""num"",
        ""int"": true,
        ""opt"": true
       },
       ""block"": {
        ""k"": ""num"",
        ""int"": true,
        ""opt"": true
       },
       ""weight"": {
        ""k"": ""num""
       },
       ""maxConsecutive"": {
        ""k"": ""num"",
        ""int"": true,
        ""opt"": true
       },
       ""effects"": {
        ""k"": ""effects"",
        ""opt"": true
       },
       ""locked"": {
        ""k"": ""bool"",
        ""opt"": true
       },
       ""delay"": {
        ""k"": ""obj"",
        ""fields"": {
         ""turns"": {
          ""k"": ""num"",
          ""int"": true
         },
         ""whileCharging"": {
          ""k"": ""obj"",
          ""fields"": {
           ""block"": {
            ""k"": ""num"",
            ""int"": true,
            ""opt"": true
           },
           ""effects"": {
            ""k"": ""effects"",
            ""opt"": true
           },
           ""intent"": {
            ""k"": ""enum"",
            ""values"": [
             ""attack"",
             ""block"",
             ""buff"",
             ""debuff"",
             ""unknown""
            ],
            ""opt"": true
           }
          },
          ""opt"": true
         }
        },
        ""opt"": true
       }
      }
     }
    },
    ""firstMove"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""phases"": {
     ""k"": ""arr"",
     ""of"": {
      ""k"": ""obj"",
      ""fields"": {
       ""on"": {
        ""k"": ""enum"",
        ""values"": [
         ""combatStart"",
         ""combatEnd"",
         ""playerTurnStart"",
         ""playerTurnEnd"",
         ""enemyTurnStart"",
         ""enemyTurnEnd"",
         ""enemyMoveStarted"",
         ""cardDrawn"",
         ""cardPlayed"",
         ""cardExhausted"",
         ""cardDiscarded"",
         ""deckShuffled"",
         ""armamentSwapped"",
         ""damageDealt"",
         ""blockGained"",
         ""hpLost"",
         ""healed"",
         ""statusApplied"",
         ""statusExpired"",
         ""meterFilled"",
         ""stanceEntered"",
         ""stanceExited"",
         ""enemySpawned"",
         ""enemyDied"",
         ""enemyStaggered"",
         ""procBurst"",
         ""procResisted"",
         ""energyGained"",
         ""energySpent"",
         ""manaRestored"",
         ""manaSpent"",
         ""staminaSpent"",
         ""staminaRecovered"",
         ""dodgeRolled"",
         ""arcaneExposureChanged"",
         ""arcaneExposureRefused"",
         ""arcaneBreak"",
         ""flaskUsed"",
         ""relicTriggered"",
         ""ownerTurnStart"",
         ""ownerTurnEnd"",
         ""hpBelowPct""
        ]
       },
       ""pct"": {
        ""k"": ""num"",
        ""opt"": true
       },
       ""once"": {
        ""k"": ""bool"",
        ""opt"": true
       },
       ""if"": {
        ""k"": ""predicate"",
        ""opt"": true
       },
       ""do"": {
        ""k"": ""effects""
       },
       ""unlockMoves"": {
        ""k"": ""arr"",
        ""of"": {
         ""k"": ""str""
        },
        ""opt"": true
       }
      }
     },
     ""opt"": true
    },
    ""art"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""size"": {
     ""k"": ""enum"",
     ""values"": [
      ""small"",
      ""medium"",
      ""large""
     ],
     ""opt"": true
    },
    ""tint"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""artFaces"": {
     ""k"": ""enum"",
     ""values"": [
      ""left"",
      ""right"",
      ""front""
     ],
     ""opt"": true
    },
    ""arcaneExposure"": {
     ""k"": ""union"",
     ""anyOf"": [
      {
       ""k"": ""obj"",
       ""fields"": {
        ""mode"": {
         ""k"": ""enum"",
         ""values"": [
          ""immune""
         ]
        }
       }
      },
      {
       ""k"": ""obj"",
       ""fields"": {
        ""mode"": {
         ""k"": ""enum"",
         ""values"": [
          ""configured""
         ]
        },
        ""threshold"": {
         ""k"": ""num"",
         ""int"": true
        },
        ""buildupMultiplier"": {
         ""k"": ""num""
        },
        ""resetMode"": {
         ""k"": ""enum"",
         ""values"": [
          ""zero""
         ]
        },
        ""overflowPolicy"": {
         ""k"": ""enum"",
         ""values"": [
          ""discard""
         ]
        },
        ""lockPolicy"": {
         ""k"": ""enum"",
         ""values"": [
          ""whileMagicVulnerable""
         ]
        },
        ""onBreak"": {
         ""k"": ""obj"",
         ""fields"": {
          ""status"": {
           ""k"": ""ref"",
           ""reg"": ""statuses""
          },
          ""value"": {
           ""k"": ""num""
          },
          ""duration"": {
           ""k"": ""num"",
           ""int"": true
          }
         }
        }
       }
      }
     ],
     ""opt"": true
    },
    ""damageResistanceBySchool"": {
     ""k"": ""obj"",
     ""fields"": {
      ""physical"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""magic"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""arcane"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""holy"": {
       ""k"": ""num"",
       ""opt"": true
      },
      ""fire"": {
       ""k"": ""num"",
       ""opt"": true
      }
     },
     ""opt"": true
    },
    ""script"": {
     ""k"": ""ref"",
     ""reg"": ""scripts"",
     ""opt"": true
    }
   }
  },
  ""encounters"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""enemies"": {
     ""k"": ""arr"",
     ""of"": {
      ""k"": ""ref"",
      ""reg"": ""enemies""
     }
    },
    ""weight"": {
     ""k"": ""num""
    },
    ""minFloor"": {
     ""k"": ""num"",
     ""int"": true,
     ""opt"": true
    },
    ""pool"": {
     ""k"": ""enum"",
     ""values"": [
      ""normal"",
      ""elite"",
      ""boss""
     ]
    },
    ""act"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""floorBand"": {
     ""k"": ""obj"",
     ""fields"": {
      ""min"": {
       ""k"": ""num"",
       ""int"": true
      },
      ""max"": {
       ""k"": ""num"",
       ""int"": true
      }
     }
    },
    ""targetBand"": {
     ""k"": ""obj"",
     ""fields"": {
      ""min"": {
       ""k"": ""num"",
       ""int"": true
      },
      ""max"": {
       ""k"": ""num"",
       ""int"": true
      }
     }
    }
   }
  },
  ""events"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""name"": {
     ""k"": ""str""
    },
    ""art"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""text"": {
     ""k"": ""str""
    },
    ""choices"": {
     ""k"": ""arr"",
     ""of"": {
      ""k"": ""obj"",
      ""fields"": {
       ""label"": {
        ""k"": ""str""
       },
       ""requires"": {
        ""k"": ""obj"",
        ""fields"": {
         ""cinders"": {
          ""k"": ""num"",
          ""int"": true,
          ""opt"": true
         }
        },
        ""opt"": true
       },
       ""effects"": {
        ""k"": ""effects""
       },
       ""resultText"": {
        ""k"": ""str""
       }
      }
     }
    }
   }
  },
  ""flasks"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""name"": {
     ""k"": ""str""
    },
    ""rarity"": {
     ""k"": ""enum"",
     ""values"": [
      ""common"",
      ""uncommon"",
      ""rare""
     ]
    },
    ""kind"": {
     ""k"": ""enum"",
     ""values"": [
      ""hp"",
      ""mana"",
      ""utility""
     ],
     ""opt"": true
    },
    ""targeted"": {
     ""k"": ""bool"",
     ""opt"": true
    },
    ""effects"": {
     ""k"": ""effects""
    },
    ""icon"": {
     ""k"": ""str""
    },
    ""artKey"": {
     ""k"": ""str""
    },
    ""artAsset"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""tint"": {
     ""k"": ""str""
    },
    ""textTemplate"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""script"": {
     ""k"": ""ref"",
     ""reg"": ""scripts"",
     ""opt"": true
    }
   }
  },
  ""classes"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""name"": {
     ""k"": ""str""
    },
    ""maxHp"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""startingFlaskAllocation"": {
     ""k"": ""obj"",
     ""fields"": {
      ""hp"": {
       ""k"": ""num"",
       ""int"": true
      },
      ""mana"": {
       ""k"": ""num"",
       ""int"": true
      }
     }
    },
    ""glyph"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""cardTint"": {
     ""k"": ""str"",
     ""opt"": true
    },
    ""startingRelic"": {
     ""k"": ""ref"",
     ""reg"": ""relics""
    },
    ""startingSignatureCard"": {
     ""k"": ""ref"",
     ""reg"": ""cards""
    },
    ""eligibleStartingKitIds"": {
     ""k"": ""arr"",
     ""of"": {
      ""k"": ""str""
     }
    },
    ""cardPool"": {
     ""k"": ""arr"",
     ""of"": {
      ""k"": ""ref"",
      ""reg"": ""cards""
     }
    },
    ""description"": {
     ""k"": ""str"",
     ""opt"": true
    }
   }
  },
  ""equipment.basicCardProfiles"": {
   ""k"": ""obj"",
   ""fields"": {
    ""id"": {
     ""k"": ""str""
    },
    ""role"": {
     ""k"": ""enum"",
     ""values"": [
      ""attack"",
      ""guard"",
      ""technique""
     ]
    },
    ""baseCardId"": {
     ""k"": ""ref"",
     ""reg"": ""cards""
    },
    ""displayName"": {
     ""k"": ""str""
    },
    ""icon"": {
     ""k"": ""str""
    },
    ""damageSchool"": {
     ""k"": ""enum"",
     ""values"": [
      ""physical"",
      ""magic"",
      ""arcane"",
      ""holy"",
      ""fire""
     ]
    },
    ""exposureBuildupPerHit"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""baseValue"": {
     ""k"": ""num""
    },
    ""scalingStat"": {
     ""k"": ""ref"",
     ""reg"": ""attributes""
    },
    ""pointsPerTier"": {
     ""k"": ""num""
    },
    ""rounding"": {
     ""k"": ""enum"",
     ""values"": [
      ""floor"",
      ""ceil"",
      ""round""
     ]
    },
    ""gainPerTier"": {
     ""k"": ""num""
    },
    ""cap"": {
     ""k"": ""union"",
     ""anyOf"": [
      {
       ""k"": ""num""
      },
      {
       ""k"": ""str""
      }
     ]
    },
    ""flavor"": {
     ""k"": ""str""
    },
    ""mods"": {
     ""k"": ""arr"",
     ""of"": {
      ""k"": ""str""
     }
    },
    ""compatibility"": {
     ""k"": ""enum"",
     ""values"": [
      ""attack-v1"",
      ""guard-v1"",
      ""technique-v1""
     ]
    }
   }
  }
 },
 ""objects"": {
  ""attributeRules"": {
   ""k"": ""obj"",
   ""fields"": {
    ""defaultMode"": {
     ""k"": ""ref"",
     ""reg"": ""creationModes""
    },
    ""presets"": {
     ""k"": ""map"",
     ""of"": {
      ""k"": ""map"",
      ""of"": {
       ""k"": ""map"",
       ""of"": {
        ""k"": ""num"",
        ""int"": true
       }
      }
     }
    },
    ""retired"": {
     ""k"": ""map"",
     ""of"": {
      ""k"": ""str""
     },
     ""opt"": true
    }
   }
  }
 },
 ""maps"": {
  ""mapConfigs"": {
   ""k"": ""obj"",
   ""fields"": {
    ""floors"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""columns"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""pathCount"": {
     ""k"": ""num"",
     ""int"": true
    },
    ""entries"": {
     ""k"": ""num"",
     ""int"": true,
     ""opt"": true
    },
    ""typeWeights"": {
     ""k"": ""map"",
     ""of"": {
      ""k"": ""num""
     }
    },
    ""unknownWeights"": {
     ""k"": ""map"",
     ""of"": {
      ""k"": ""num""
     },
     ""opt"": true
    },
    ""floorRules"": {
     ""k"": ""obj"",
     ""fields"": {
      ""fixed"": {
       ""k"": ""arr"",
       ""of"": {
        ""k"": ""obj"",
        ""fields"": {
         ""at"": {
          ""k"": ""enum"",
          ""values"": [
           ""first"",
           ""last"",
           ""floor"",
           ""fraction""
          ]
         },
         ""index"": {
          ""k"": ""num"",
          ""int"": true,
          ""opt"": true
         },
         ""of"": {
          ""k"": ""num"",
          ""opt"": true
         },
         ""type"": {
          ""k"": ""enum"",
          ""values"": [
           ""monster"",
           ""event"",
           ""elite"",
           ""shrine"",
           ""merchant"",
           ""treasure"",
           ""boss""
          ]
         }
        }
       },
       ""opt"": true
      },
      ""noShrineBefore"": {
       ""k"": ""obj"",
       ""fields"": {
        ""at"": {
         ""k"": ""enum"",
         ""values"": [
          ""first"",
          ""last"",
          ""floor"",
          ""fraction""
         ]
        },
        ""index"": {
         ""k"": ""num"",
         ""int"": true,
         ""opt"": true
        },
        ""of"": {
         ""k"": ""num"",
         ""opt"": true
        }
       },
       ""opt"": true
      },
      ""noEliteBefore"": {
       ""k"": ""obj"",
       ""fields"": {
        ""at"": {
         ""k"": ""enum"",
         ""values"": [
          ""first"",
          ""last"",
          ""floor"",
          ""fraction""
         ]
        },
        ""index"": {
         ""k"": ""num"",
         ""int"": true,
         ""opt"": true
        },
        ""of"": {
         ""k"": ""num"",
         ""opt"": true
        }
       },
       ""opt"": true
      },
      ""noShrineOn"": {
       ""k"": ""obj"",
       ""fields"": {
        ""at"": {
         ""k"": ""enum"",
         ""values"": [
          ""first"",
          ""last"",
          ""floor"",
          ""fraction""
         ]
        },
        ""index"": {
         ""k"": ""num"",
         ""int"": true,
         ""opt"": true
        },
        ""of"": {
         ""k"": ""num"",
         ""opt"": true
        }
       },
       ""opt"": true
      },
      ""restBeforeElite"": {
       ""k"": ""bool"",
       ""opt"": true
      },
      ""minElites"": {
       ""k"": ""num"",
       ""int"": true,
       ""opt"": true
      },
      ""minMerchants"": {
       ""k"": ""num"",
       ""int"": true,
       ""opt"": true
      }
     },
     ""opt"": true
    }
   }
  }
 },
 ""effectSpecs"": {
  ""damage"": {
   ""allowed"": [
    ""hits"",
    ""tags""
   ],
   ""required"": [
    ""amount""
   ],
   ""refs"": {}
  },
  ""block"": {
   ""allowed"": [],
   ""required"": [
    ""amount""
   ],
   ""refs"": {}
  },
  ""dodgeRoll"": {
   ""allowed"": [],
   ""required"": [],
   ""refs"": {}
  },
  ""applyStatus"": {
   ""allowed"": [
    ""status"",
    ""stacks""
   ],
   ""required"": [
    ""status""
   ],
   ""refs"": {
    ""status"": ""statuses""
   }
  },
  ""removeStatus"": {
   ""allowed"": [
    ""status""
   ],
   ""required"": [
    ""status""
   ],
   ""refs"": {
    ""status"": ""statuses""
   }
  },
  ""draw"": {
   ""allowed"": [],
   ""required"": [
    ""amount""
   ],
   ""refs"": {}
  },
  ""discard"": {
   ""allowed"": [
    ""random""
   ],
   ""required"": [],
   ""refs"": {}
  },
  ""exhaust"": {
   ""allowed"": [
    ""random""
   ],
   ""required"": [],
   ""refs"": {}
  },
  ""addCard"": {
   ""allowed"": [
    ""card"",
    ""pile"",
    ""position"",
    ""count""
   ],
   ""required"": [
    ""card""
   ],
   ""refs"": {
    ""card"": ""cards""
   }
  },
  ""gainEnergy"": {
   ""allowed"": [],
   ""required"": [
    ""amount""
   ],
   ""refs"": {}
  },
  ""restoreMana"": {
   ""allowed"": [],
   ""required"": [
    ""amount""
   ],
   ""refs"": {}
  },
  ""loseHp"": {
   ""allowed"": [
    ""cause""
   ],
   ""required"": [
    ""amount""
   ],
   ""refs"": {}
  },
  ""heal"": {
   ""allowed"": [],
   ""required"": [
    ""amount""
   ],
   ""refs"": {}
  },
  ""shuffleDiscardIntoDraw"": {
   ""allowed"": [],
   ""required"": [],
   ""refs"": {}
  },
  ""enterStance"": {
   ""allowed"": [
    ""stance""
   ],
   ""required"": [
    ""stance""
   ],
   ""refs"": {
    ""stance"": ""stances""
   }
  },
  ""poiseDamage"": {
   ""allowed"": [],
   ""required"": [
    ""amount""
   ],
   ""refs"": {}
  },
  ""stagger"": {
   ""allowed"": [],
   ""required"": [],
   ""refs"": {}
  },
  ""addCinders"": {
   ""allowed"": [],
   ""required"": [
    ""amount""
   ],
   ""refs"": {}
  },
  ""addCardToDeck"": {
   ""allowed"": [
    ""card""
   ],
   ""required"": [
    ""card""
   ],
   ""refs"": {
    ""card"": ""cards""
   }
  },
  ""removeCardFromDeck"": {
   ""allowed"": [
    ""card"",
    ""random""
   ],
   ""required"": [],
   ""refs"": {
    ""card"": ""cards""
   }
  },
  ""upgradeCard"": {
   ""allowed"": [
    ""card"",
    ""random""
   ],
   ""required"": [],
   ""refs"": {
    ""card"": ""cards""
   }
  },
  ""addRelic"": {
   ""allowed"": [
    ""id"",
    ""random""
   ],
   ""required"": [],
   ""refs"": {
    ""id"": ""relics""
   }
  },
  ""addFlask"": {
   ""allowed"": [
    ""id"",
    ""random""
   ],
   ""required"": [],
   ""refs"": {
    ""id"": ""flasks""
   }
  },
  ""addFlaskCapacity"": {
   ""allowed"": [
    ""kind"",
    ""amount""
   ],
   ""required"": [
    ""kind"",
    ""amount""
   ],
   ""refs"": {}
  },
  ""loseMaxHpPct"": {
   ""allowed"": [
    ""pct""
   ],
   ""required"": [
    ""pct""
   ],
   ""refs"": {}
  },
  ""startCombat"": {
   ""allowed"": [
    ""encounterId""
   ],
   ""required"": [
    ""encounterId""
   ],
   ""refs"": {
    ""encounterId"": ""encounters""
   }
  }
 },
 ""commonEffectFields"": [
  ""op"",
  ""target"",
  ""amount"",
  ""if"",
  ""repeat""
 ],
 ""opcodes"": [
  ""damage"",
  ""block"",
  ""dodgeRoll"",
  ""applyStatus"",
  ""removeStatus"",
  ""draw"",
  ""discard"",
  ""exhaust"",
  ""addCard"",
  ""gainEnergy"",
  ""restoreMana"",
  ""loseHp"",
  ""heal"",
  ""shuffleDiscardIntoDraw"",
  ""enterStance"",
  ""poiseDamage"",
  ""stagger"",
  ""addCinders"",
  ""addCardToDeck"",
  ""removeCardFromDeck"",
  ""upgradeCard"",
  ""addRelic"",
  ""addFlask"",
  ""addFlaskCapacity"",
  ""loseMaxHpPct"",
  ""startCombat""
 ],
 ""targets"": [
  ""self"",
  ""enemy"",
  ""allEnemies"",
  ""randomEnemy"",
  ""player"",
  ""owner"",
  ""ally""
 ],
 ""triggerEvents"": [
  ""combatStart"",
  ""combatEnd"",
  ""playerTurnStart"",
  ""playerTurnEnd"",
  ""enemyTurnStart"",
  ""enemyTurnEnd"",
  ""enemyMoveStarted"",
  ""cardDrawn"",
  ""cardPlayed"",
  ""cardExhausted"",
  ""cardDiscarded"",
  ""deckShuffled"",
  ""armamentSwapped"",
  ""damageDealt"",
  ""blockGained"",
  ""hpLost"",
  ""healed"",
  ""statusApplied"",
  ""statusExpired"",
  ""meterFilled"",
  ""stanceEntered"",
  ""stanceExited"",
  ""enemySpawned"",
  ""enemyDied"",
  ""enemyStaggered"",
  ""procBurst"",
  ""procResisted"",
  ""energyGained"",
  ""energySpent"",
  ""manaRestored"",
  ""manaSpent"",
  ""staminaSpent"",
  ""staminaRecovered"",
  ""dodgeRolled"",
  ""arcaneExposureChanged"",
  ""arcaneExposureRefused"",
  ""arcaneBreak"",
  ""flaskUsed"",
  ""relicTriggered"",
  ""ownerTurnStart"",
  ""ownerTurnEnd"",
  ""hpBelowPct""
 ],
 ""triggerFields"": [
  ""on"",
  ""if"",
  ""do"",
  ""once"",
  ""limitPerTurn""
 ],
 ""predicates"": [
  ""inStance"",
  ""hasStatus"",
  ""hasBlock"",
  ""hpBelowPct"",
  ""firstCardThisTurn"",
  ""firstAttackThisCombat"",
  ""cardTypeIs"",
  ""everyNthCardThisCombat"",
  ""random"",
  ""eventIsAttack"",
  ""eventSourceIsOwner"",
  ""eventTargetIsOwner"",
  ""eventStatusIs"",
  ""all"",
  ""any"",
  ""not""
 ],
 ""predicateFields"": {
  ""inStance"": [
   ""stance""
  ],
  ""hasStatus"": [
   ""of"",
   ""status"",
   ""atLeast""
  ],
  ""hasBlock"": [
   ""of""
  ],
  ""hpBelowPct"": [
   ""of"",
   ""pct""
  ],
  ""firstCardThisTurn"": [],
  ""firstAttackThisCombat"": [],
  ""cardTypeIs"": [
   ""type""
  ],
  ""everyNthCardThisCombat"": [
   ""n""
  ],
  ""random"": [
   ""pct""
  ],
  ""eventIsAttack"": [],
  ""eventSourceIsOwner"": [],
  ""eventTargetIsOwner"": [],
  ""eventStatusIs"": [
   ""status""
  ],
  ""all"": [
   ""preds""
  ],
  ""any"": [
   ""preds""
  ],
  ""not"": [
   ""pred""
  ]
 },
 ""predicateOf"": [
  ""self"",
  ""owner"",
  ""player"",
  ""enemy"",
  ""target""
 ],
 ""formulaOps"": [
  ""add"",
  ""mul"",
  ""percentMaxHp"",
  ""missingHp"",
  ""stacks"",
  ""energySpent"",
  ""blockOf"",
  ""hpOf"",
  ""cardsPlayedThisTurn""
 ],
 ""formulaOf"": [
  ""self"",
  ""owner"",
  ""target"",
  ""enemy"",
  ""player"",
  ""allEnemies""
 ],
 ""formulaFields"": {
  ""add"": [
   ""args""
  ],
  ""mul"": [
   ""args""
  ],
  ""percentMaxHp"": [
   ""of"",
   ""pct"",
   ""min"",
   ""max""
  ],
  ""missingHp"": [
   ""of"",
   ""min"",
   ""max""
  ],
  ""stacks"": [
   ""status"",
   ""of"",
   ""per"",
   ""min"",
   ""max""
  ],
  ""energySpent"": [
   ""per"",
   ""min"",
   ""max""
  ],
  ""blockOf"": [
   ""of"",
   ""min"",
   ""max""
  ],
  ""hpOf"": [
   ""of"",
   ""min"",
   ""max""
  ],
  ""cardsPlayedThisTurn"": [
   ""per"",
   ""min"",
   ""max""
  ]
 },
 ""cardTypes"": [
  ""attack"",
  ""skill"",
  ""power"",
  ""curse"",
  ""status""
 ],
 ""damageSchools"": [
  ""physical"",
  ""magic"",
  ""arcane"",
  ""holy"",
  ""fire""
 ],
 ""piles"": [
  ""draw"",
  ""hand"",
  ""discard"",
  ""exhaust""
 ],
 ""pilePositions"": [
  ""top"",
  ""bottom"",
  ""random""
 ]
}";
    }
}
