// RunController.cs
// PURPOSE: connects the deterministic expedition model to the touch UI and save adapter.
// ATTACH: one instance on the ExpeditionRoot prefab in Scenes/Expedition.unity.
// INSPECTOR: assign the generated PanelSettings asset. Content and theme are imported
// by AshenSpire > Import Content into Resources; missing configuration fails visibly.
// LIFECYCLE: OnEnable binds the view; OnDisable unbinds/saves. Pause saves.
// Update only adjusts panel scaling when viewport height changes, keeping landscape readable.
// EDIT DATA: GameContent/Unity/expedition.json. EDIT UI: Presentation/ExpeditionView.cs and
// Resources/Expedition.uss. EDIT RULES: Domain/RunSession.cs, never the button callbacks.
// STATE: RunSession owns combat. PlayerPrefs stores a versioned, channel-specific snapshot.
// VERIFY: begin, select/play card, end turn, reach reward, resume after reloading browser.
// FAILURE: missing cards/art => Import Content; missing UI => check PanelSettings reference.
using System;
using AshenSpire.Domain;
using AshenSpire.Presentation;
using UnityEngine;
using UnityEngine.UIElements;

namespace AshenSpire.Application
{
    [RequireComponent(typeof(UIDocument))]
    public sealed class RunController : MonoBehaviour
    {
        [SerializeField, Tooltip("Shared panel configuration generated by BuildTools. Controls phone scaling.")]
        private PanelSettings _panelSettings;
        private ContentDefinition _content;
        private RunSession _session;
        private ExpeditionView _view;
        private string _saveKey;
        private int _screenHeight;
        private bool _diagnosticsEnabled;

        public void Configure(PanelSettings settings) => _panelSettings = settings;

        private void OnEnable()
        {
            try
            {
                var document = GetComponent<UIDocument>();
                if (_panelSettings == null) throw new InvalidOperationException("Assign PanelSettings on ExpeditionRoot.");
                document.panelSettings = _panelSettings;
                var source = Resources.Load<TextAsset>("expedition");
                if (source == null) throw new InvalidOperationException("Import Content before playing.");
                _content = JsonUtility.FromJson<ContentDefinition>(source.text); _content.Validate();
                // Same-origin Pages channels must never share an expedition save.
                var path = "editor";
                if (Uri.TryCreate(UnityEngine.Application.absoluteURL, UriKind.Absolute, out var uri))
                {
                    var segments = uri.AbsolutePath.Split('/');
                    path = "web";
                    foreach (var segment in segments)
                        if (segment == "dev" || segment == "test" || segment == "release" || segment == "main") { path = segment; break; }
                }
                _saveKey = "AshenSpire.Unity.Expedition.v1." + path;
                _diagnosticsEnabled = path == "dev" || path == "editor" || (uri != null && uri.IsLoopback);
                _view = new ExpeditionView(document.rootVisualElement);
                _view.StartRequested += StartRun; _view.ContinueRequested += Resume;
                _view.EnterRequested += Enter; _view.CardRequested += Play;
                _view.EndTurnRequested += EndTurn; _view.RewardRequested += Reward;
                _view.MenuRequested += Menu;
                _view.ShowTitle(PlayerPrefs.HasKey(_saveKey));
                Debug.Log("ASHENSPIRE_UI_READY");
            }
            catch (Exception error) { Debug.LogException(error); }
        }

        private void StartRun()
        { Bind(new RunSession(_content, (uint)DateTime.UtcNow.Ticks)); Refresh(); }
        private void Resume()
        {
            try { Bind(new RunSession(_content, JsonUtility.FromJson<RunState>(PlayerPrefs.GetString(_saveKey)))); Refresh(); }
            catch (Exception error) { Debug.LogWarning(error.Message); _view.ShowTitle(false, "This save could not be loaded. It has been preserved."); }
        }
        private void Bind(RunSession session)
        { if (_session != null) _session.Changed -= Refresh; _session = session; _session.Changed += Refresh; }
        private void Enter() => _session?.EnterEncounter();
        private void Play(int index)
        {
            if (_session == null || index < 0 || index >= _session.State.Hand.Count) return;
            var attack = _session.GetCard(_session.State.Hand[index]).HasTag("attack");
            if (_session.PlayCard(index) && attack) _view.PlayAttack();
        }
        private void EndTurn() => _session?.EndTurn();
        private void Reward(string id) => _session?.ClaimReward(id);
        private void Menu() { Save(); _view.ShowTitle(PlayerPrefs.HasKey(_saveKey)); }
        private void Refresh()
        {
            Save(); _view.Render(_session);
            // Read-only local/dev diagnostics let tests verify real commands and resume,
            // independently of harmless pixel rounding differences after a reload.
            if (_diagnosticsEnabled) Debug.Log("ASHENSPIRE_STATE " + JsonUtility.ToJson(_session.State));
        }
        private void Save()
        {
            if (_session == null || string.IsNullOrEmpty(_saveKey)) return;
            PlayerPrefs.SetString(_saveKey, JsonUtility.ToJson(_session.State)); PlayerPrefs.Save();
        }
        private void OnApplicationPause(bool paused) { if (paused) Save(); }
        private void Update()
        {
            if (_panelSettings == null || _screenHeight == Screen.height) return;
            _screenHeight = Screen.height;
            _panelSettings.referenceResolution = new Vector2Int(430, Screen.height < 600 ? Screen.height : 900);
        }
        private void OnDisable()
        {
            Save();
            if (_session != null) _session.Changed -= Refresh;
            if (_view == null) return;
            _view.StartRequested -= StartRun; _view.ContinueRequested -= Resume;
            _view.EnterRequested -= Enter; _view.CardRequested -= Play;
            _view.EndTurnRequested -= EndTurn; _view.RewardRequested -= Reward;
            _view.MenuRequested -= Menu;
        }
    }
}
