import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {collectHistory} from './unity-build-history.mjs';
import {attachBuildReviews} from './unity-build-reviews.mjs';
const base=path.resolve('Builds/ReviewTests');fs.mkdirSync(base,{recursive:true});
const root=fs.mkdtempSync(path.join(base,'case-'));
const git=args=>execFileSync('git',args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
const write=(file,value)=>{const full=path.join(root,file);fs.mkdirSync(path.dirname(full),{recursive:true});fs.writeFileSync(full,typeof value==='string'?value:JSON.stringify(value));};
const commit=message=>{git(['add','Published']);git(['commit','-m',message]);return git(['rev-parse','HEAD']);};
git(['init']);git(['config','user.name','Review fixture']);git(['config','user.email','review@example.invalid']);
const manifest={version:'0.0.22.0',buildNumber:22,sourceDigest:'a'.repeat(64),files:{}};
write('Published/Web/index.html','original player');write('Published/build.json',manifest);
const original=commit('Original player');
const proof={...manifest,currentPlayerSuites:[{suite:'captured',success:true}],ownerAccepted:false};
const presentation={guide:'Published/Review/Guide.md',screenshots:['Published/Review/phone.png']};
write('Published/validation.json',proof);write('Published/presentation.json',presentation);
write(presentation.guide,'Review notes');write(presentation.screenshots[0],'image fixture');
const reviewed=commit('Later review only');
const history=()=>collectHistory(root,{dev:'HEAD'});
let checks=0;const check=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
const attached=attachBuildReviews(root,history(),['HEAD']);
check('later evidence keeps one immutable player',()=>assert.equal(attached.builds.length,1));
check('original download commit remains unchanged',()=>assert.equal(attached.builds[0].commit,original));
check('review uses the later committed capture',()=>assert.equal(attached.builds[0].review.commit,reviewed));
check('review paths are explicit committed files',()=>assert.deepEqual(attached.builds[0].review.screenshots,presentation.screenshots));
write('Published/validation.json',{...proof,sourceDigest:'b'.repeat(64)});commit('Wrong source proof');
check('a different compiled source cannot supply screenshots',()=>assert.equal(attachBuildReviews(root,history(),['HEAD']).builds[0].review,undefined));
write('Published/validation.json',proof);write('Published/Web/index.html','changed runtime without a new export manifest');commit('Changed runtime');
check('matching metadata cannot hide different actual Web bytes',()=>assert.equal(attachBuildReviews(root,history(),['HEAD']).builds[0].review,undefined));
write('Published/Web/index.html','original player');write('Published/validation.json',{...proof,currentPlayerSuites:[{success:false}]});commit('Failed capture');
check('failed capture cannot become current review evidence',()=>assert.equal(attachBuildReviews(root,history(),['HEAD']).builds[0].review,undefined));
write('Published/validation.json',proof);write('Published/presentation.json',{...presentation,guide:'Published/Review/missing.md'});commit('Missing review file');
check('missing matching review files fail visibly',()=>assert.throws(()=>attachBuildReviews(root,history(),['HEAD']),/not committed/));
write('Published/presentation.json',{...presentation,guide:'Published/../escape.md'});commit('Unsafe review path');
check('review paths cannot escape Published',()=>assert.throws(()=>attachBuildReviews(root,history(),['HEAD'])));
console.log(checks+' review evidence checks passed');
